services:
  - type: worker
    name: vulkan-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: ./render-build.sh
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DISCORD_TOKEN
        sync: false
